#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim options are below [options] snippet
[options]
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer, the value of this option is a string.
  colorscheme = "one"
  colorscheme_bg = "dark"
  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors, the type of the value is boolean, true or false.
  enable_guicolors = true
  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  statusline_separator = "arrow"
  buffer_index_type = 4
  # Display file type icon on the tabline, If you do not have nerd fonts
  # installed, please change the value to false
  enable_tabline_filetype_icon = true
  filetree_direction = "left"
  # Display current mode text on statusline, by default It is disabled,
  # only color will be changed when switch modes.
  enable_statusline_mode = false
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
  relativenumber = false
  default_indent = 4
  bootstrap_before = "myspacevim#before"
  bootstrap_after  = "myspacevim#after"
  autocomplete_method = 'coc'
  # autocomplete_method = 'deoplete'
  guifont = "FiraCode Nerd Font:h14"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'checkers'
enable_neomake = false
enable_ale = true
show_cursor_error = false

[[layers]]
name = 'colorscheme'

[[layers]]
name = 'debug'

[[layers]]
name = 'denite'

[[layers]]
name = "format"
format_on_save = true

[[layers]]
name = 'git'

[[layers]]
name = 'gtags'

[[layers]]
name = 'VersionControl'

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 20

[[layers]]
name = 'test'

[[layers]]
name = 'ui'
enable_indentline = false

[[layers]]
name = 'lsp'
filetypes = [
  'c',
  'cpp',
  'css',
  'go',
  'haskell',
  'html',
  'javascript',
  'kotlin',
  'python',
  'ruby',
  'rust',
  'sh',
  'typescript'
]
[layers.override_cmd]
  go = ["gopls"]
  haskell = ["haskell-language-server-wrapper", "--lsp"]
  kotlin = ["kotlin-language-server"]
  rust = ["rust-analyzer"]

[[layers]]
name = 'lang#c'
# enable_clang_syntax_highlight = 1

[[layers]]
name = 'lang#clojure'

[[layers]]
name = 'lang#csharp'
highlight_types = 3

[[layers]]
name = 'lang#dockerfile'

[[layers]]
name = 'lang#elixir'

[[layers]]
name = 'lang#elm'

[[layers]]
name = 'lang#fsharp'
format_on_save = true

[[layers]]
name = 'lang#go'

[[layers]]
name = 'lang#haskell'
recomended-style = 1
format-autosave = 1

[[layers]]
name = 'lang#html'

[[layers]]
name = 'lang#java'

[[layers]]
name = 'lang#javascript'
auto_fix = true

[[layers]]
name = 'lang#json'

[[layers]]
name = 'lang#kotlin'

[[layers]]
name = 'lang#lisp'

[[layers]]
name = 'lang#markdown'

[[layers]]
name = 'lang#ocaml'

[[layers]]
name = 'lang#perl'

[[layers]]
name = 'lang#python'
format-on-save = 1
enable_typeinfo = true
python_file_head = []

[[layers]]
name = 'lang#red'

[[layers]]
name = 'lang#ruby'
repl_command = 'pry'

[[layers]]
name = 'lang#rust'
recomended_style = true
format_on_save = true

[[layers]]
name = 'lang#scala'

[[layers]]
name = 'lang#scheme'
scheme_dialect = 'gauche'
scheme_interpreter = '/usr/local/bin/gosh'

# [[layers]]
# name = 'lang#sql'

[[layers]]
name = 'lang#toml'

[[layers]]
name = 'lang#typescript'

[[layers]]
name = 'lang#vue'
